---
default_config:

homeassistant:
  name: Home
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true
    - type: homeassistant

logger:
  default: error

