export const GENERIC_LABELS = [
  "color",
  "icon",
  "icon_color",
  "icon_animation",
  "layout",
  "fill_container",
  "primary_info",
  "secondary",
  "secondary_info",
  "icon_type",
  "content_info",
  "use_entity_picture",
  "collapsible_controls",

  // "key",
  // "name",
  // "description",
  // "selector",
  // "required",
  "disabled",
  "show_state",
  "value",
  "entity",
  "title",
  "layout",
  "expandable",
  "save_label",
  "spread_values_to_data",
  "reset_on_submit",
  "save_action",
];
